t7800: try harder to fall back to a valid temp directory
On Windows, there simply is no `/tmp/`. Hence t7800.46 "difftool
--dir-diff avoids repeated slashes in TMPDIR --no-symlinks" fails
(without this patch), thusly:

  + TMPDIR=/tmp//// git difftool --dir-diff --no-symlinks --extcmd echo branch
  error: could not create '/tmp/git-difftool.a23912'

Signed-off-by: Johannes Schindelin <johannes.schindelin@gmx.de>